- name: Install home ca certificate
  command:
    cmd: trust anchor --store roles/misc/files/certificates/root-ca-home.pem
  notify: on_trust_certificate
- name: Install bitwarden.home certificate
  command:
    cmd: trust anchor --store roles/misc/files/certificates/bitwarden.home.pem
  notify: on_trust_certificate
- name: Create custom certificates directory
  file:
    path: /opt/custom-certificates
    state: directory
- name: Copy custom certificates
  synchronize:
    src: certificates/
    dest: /opt/custom-certificates