- name: AUR pre-requisits
  community.general.pacman:
    name: base-devel
    state: present
- name: Install git
  community.general.pacman:
    name: git
    state: present
- name: Install Golang (also needed to install yay)
  community.general.pacman:
    name: go
    state: present
- name: Clone yay
  when: "'/usr/bin/yay' is not exists" 
  become: false
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay-clone
- name: Build and install yay
  when: "'/usr/bin/yay' is not exists" 
  become: false
  command:
    # cmd: sudo -H -u {{ lookup('env', 'USER') }} bash -c 'makepkg -si'
    cmd: makepkg -si --noconfirm
    chdir: /tmp/yay-clone
    creates: /usr/bin/yay