- include_tasks: common.yaml
- include_tasks: yay.yaml
- include_tasks: ripgrep.yaml
- include_tasks: tmux.yaml
- include_tasks: alacritty.yaml
- include_tasks: neovim.yaml
- include_tasks: unzip.yaml
- include_tasks: i3.yaml